version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  my-api:
    build:
      context: .
      dockerfile: MyApi/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__Default: "Host=postgres;Database=orders;Username=postgres;Password=postgres"
      Rabbit__Host: rabbitmq
    ports:
      - "5000:8080"

  worker-service1:
    build:
      context: .
      dockerfile: WorkerService1/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    environment:
      ConnectionStrings__Default: "Host=postgres;Database=orders;Username=postgres;Password=postgres"
      Rabbit__Host: rabbitmq

volumes:
  pgdata:
